<wsdl:definitions name="RestReference" targetNamespace="http://xmlns.oracle.com/RESTApplication/HotelByCityIdService/RestReference" xmlns:tns="http://xmlns.oracle.com/RESTApplication/HotelByCityIdService/RestReference" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:include schemaLocation="../schemas/HotelByCityId_request.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:include schemaLocation="../schemas/RestReference_response.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="requestRestReference" element="Request"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="responseRestReferece" element="responseRestReference"/>
    </wsdl:message>
    <wsdl:portType name="RestReference_ptt">
        <wsdl:operation name="RestReference">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RestReference_bind" type="tns:RestReference_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="RestReference">
            <soap:operation style="document" soapAction="RestReference"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/RESTApplication/HotelByCityIdService/RestReference"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/RESTApplication/HotelByCityIdService/RestReference"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>